services:
  devnode:
    build:
      context: ./api
      target: dev
    volumes:
      - ./api/index.js:/src/index.js
  nginx:
    image: nginx:1-alpine
    ports:
      - 8089:80
    volumes:
      - ./html/:/usr/share/nginx/html
      - ./ngconf/default.conf:/etc/nginx/conf.d/default.conf

